org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.89
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=perk_weapons
mod_name=Perk Weapons
mod_license=All Rights Reserved
mod_version=1.21.1-neoforge-1.1.4-beta
mod_group_id=net.akashi.perk_weapons
mod_authors=AkashiTheCat
mod_description=Weapons with perks!
